# Configuration file for ScriptEx
#
# Written by Haohan Liu (c) 2020


---
# Program operating parameters
Program:
    DisableSystemCheck: false
    AutoWinUpdate: true
    IgnoreInvalidCommands: false
    SetPerformanceMode: true
    TitleScreenDelay: 50
    InvokeReflectionKey: "/"

    DefaultMode: "!s"
    ModeKeys:
        "!s": Software
        "!t": Testing
        "!u": Utility
        "!q": QC

    SpecialKeys:
        "|": Threadblock
        "?": Show Commands
      
      
# RoboCopy operating parameters
RoboCopy:
    SrcDriveName: SAMSUNG USB
    SrcDriveRoot: ~
    SrcDriveType: Removable 

    ForceSrcDriveLetter: false
    SrcDriveLetter: D

    # To be implemented
    SrcUseNetwork: false
    SrcPreferNetwork: false
    SrcNetworkRoot: "\\\\cache\\SI Software"


# Modes of operation
Modes:
    # Software installation command configuration
    Software:
        SrcCopy: true
        SrcModeRoot: SOFTWARE
        DstModeRoot: "%USERPROFILE%\\Desktop\\Setup"

        Categories:
            - driver
            - lighting

        Commands:
            # Hardware Drivers
            nv:
                Name: NVIDIA GPU Driver
                Category: driver
                Exec: setup.exe
                Args: -noreboot -nosplash
                Path: _NVIDIA GPU
                Delay: 0
                IgnoreThreadBlock: false
            na:
                Name: NVIDIA GPU Auto Installer
                Category: driver
                Exec: NV_INSTALL.exe
                Args: ~
                Path: _NVIDIA AUTO
                Delay: 0
                IgnoreThreadBlock: false
            amd:
                Name: AMD GPU Driver
                Category: driver
                Exec: Setup.exe
                Args: ~
                Path: _AMD GPU
                Delay: 0
                IgnoreThreadBlock: false
            amds:
                Name: AMD GPU Driver (silent)
                Category: driver
                Exec: Setup.exe
                Args: -INSTALL
                Path: _AMD GPU
                Delay: 0
                IgnoreThreadBlock: false
            amc:
                Name: AMD Chipset Driver
                Category: driver
                Exec: "*.exe"
                Args: ~
                Path: _AMD Chipset
                Delay: 0
                IgnoreThreadBlock: false
            ig:
                Name: Intel iGPU Driver
                Category: driver
                Exec: igxpin.exe
                Args: -s -overwrite
                Path: _INTEL iGPU
                Delay: 0
                IgnoreThreadBlock: false
    
            # Lighting Software
            aw:
                Name: AMD Wraith Prism (manual)
                Category: lighting
                Exec: Setup.exe
                Args: ~
                Path: AMD Wraith Prism
                Delay: 0
                IgnoreThreadBlock: false
            au:
                Name: ASUS Aura
                Category: lighting
                Exec: AsusSetup.exe
                Args: /s /SMS
                Path: ASUS Aura
                Delay: 0
                IgnoreThreadBlock: false
            aug:
                Name: ASUS Aura (GPU Only)
                Category: lighting
                Exec: AsusSetup.exe
                Args: /s /SMS
                Path: ASUS Aura GPU
                Delay: 0
                IgnoreThreadBlock: false
            ac:
                Name: ASUS Armory Crate
                Category: lighting
                Exec: "*.exe"
                Args: ~
                Path: ASUS Armory Crate
                Delay: 0
                IgnoreThreadBlock: false
            al:
                Name: ASUS LiveDash
                Category: lighting
                Exec: AsusSetup.exe
                Args: /s /SMS
                Path: ASUS LiveDash
                Delay: 0
                IgnoreThreadBlock: false
            cm:
                Name: CM MasterPlus
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP-
                Path: CM MasterPlus
                Delay: 0
                IgnoreThreadBlock: false
            tb:
                Name: TEAM Blitz
                Category: lighting
                Exec: Setup.exe
                Args: /s /SMS
                Path: TEAM Blitz
                Delay: 0
                IgnoreThreadBlock: false
            ci:
                Name: CORSAIR iCUE
                Category: lighting
                Exec: "*.msi"
                Args: /qb
                Path: CORSAIR iCUE
                Delay: 0
                IgnoreThreadBlock: false
            mm:
                Name: MSI Mystic Light
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP- 
                Path: MSI Mystic Light
                Delay: 0
                IgnoreThreadBlock: false
            md2:
                Name: MSI Dragon Center v2
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP- 
                Path: MSI Dragon Center 2
                Delay: 0
                IgnoreThreadBlock: false
            md2s:
                Name: MSI Dragon Center OneDC_SDK
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP- 
                Path: MSI OneDC_SDK
                Delay: 0
                IgnoreThreadBlock: false
            nc:
                Name: NZXT CAM
                Category: lighting
                Exec: "*.exe"
                Args: ~ 
                Path: NZXT CAM
                Delay: 0
                IgnoreThreadBlock: false
            gr:
                Name: GIGABYTE RGBFusion
                Category: lighting
                Exec: UpdPack.exe
                Args: ~
                Path: GIGABYTE RGBFusion
                Delay: 0
                IgnoreThreadBlock: false
            ga:
                Name: GIGABYTE Aorus Engine
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP-
                Path: GIGABYTE Aorus Engine
                Delay: 0
                IgnoreThreadBlock: false

    # Testing suite command configuration
    Testing:
        SrcCopy: false
        SrcModeRoot: AAA Testing
        DstModeRoot: "%USERPROFILE%\\Desktop\\AAA Testing"

        Categories:
            - cpu + ram
            - gpu
            - other

        Commands:
            p:
                Name: Prime95 (Blend)
                Category: cpu + ram
                Exec: prime95.exe
                Args: -t
                Path: Benchmark
                Delay: 5000
                IgnoreThreadBlock: false
            f:
                Name: Furmark (inf)
                Category: gpu
                Exec: FurMark.exe
                Args: /nogui /msaa=8 /width=1280 height=720 /xtreme_burning
                Path: Benchmark
                Delay: 0
                IgnoreThreadBlock: false
            f15:
                Name: Furmark (15 min)
                Category: gpu
                Exec: FurMark.exe
                Args: /nogui /msaa=8 /width=1280 height=720 /max_time=900000 /xtreme_burning
                Path: Benchmark
                Delay: 0
                IgnoreThreadBlock: false
            f25:
                Name: Furmark (25 min)
                Category: gpu
                Exec: FurMark.exe
                Args: /nogui /msaa=8 /width=1280 height=720 /max_time=1500000 /xtreme_burning
                Path: Benchmark
                Delay: 0
                IgnoreThreadBlock: false
            a:
                Name: AIDA64 Stability Test (inf)
                Category: cpu + ram
                Exec: aida64.exe
                Args: /SST CPU,FPU,Cache,RAM
                Path: AIDA64
                Delay: 1000
                IgnoreThreadBlock: false
            a15:
                Name: AIDA64 Stability Test (15 min)
                Category: cpu + ram
                Exec: aida64.exe
                Args: /SST CPU,FPU,Cache,RAM /SSTDUR 15
                Path: AIDA64
                Delay: 1000
                IgnoreThreadBlock: false
            a25:
                Name: AIDA64 Stability Test (25 min)
                Category: cpu + ram
                Exec: aida64.exe
                Args: /SST CPU,FPU,Cache,RAM /SSTDUR 25
                Path: AIDA64
                Delay: 1000
                IgnoreThreadBlock: false
            m:
                Name: HWMonitor
                Category: other
                Exec: HWMonitor_x64.exe
                Args: ~
                Path: Benchmark
                Delay: 0
                IgnoreThreadBlock: true
            s:
                Name: Superposition
                Category: gpu
                Exec: launcher.exe
                Args: ~
                Path: Benchmark\Superposition\bin
                Delay: 0
                IgnoreThreadBlock: false
            h:
                Name: Heaven
                Category: gpu
                Exec: heaven_modified.bat
                Args: ~
                Path: Benchmark\Heaven
                Delay: 0
                IgnoreThreadBlock: false
            i:
                Name: Intel Burn Test V2
                Category: cpu + ram
                Exec: IntelBurnTestV2.exe
                Args: ~
                Path: "IBT\\IntelBurnTestV2.New"
                Delay: 0
                IgnoreThreadBlock: false
            
    # QC suite command configuration
    QC:
        SrcCopy: false
        SrcModeRoot: AAA Testing
        DstModeRoot: "%USERPROFILE%\\Desktop\\AAA Testing"
            
        Commands:
            t:
                Name: Task Manager
                Exec: Task Manager.lnk
                Args: ~
                Path: QC
                Delay: 0
                IgnoreThreadBlock: false
            dv:
                Name: Device Manager
                Exec: devmgmt.msc.lnk
                Args: ~
                Path: QC
                Delay: 0
                IgnoreThreadBlock: false
            ds:
                Name: Disk Management
                Exec: diskmgmt.msc.lnk
                Args: ~
                Path: QC
                Delay: 0
                IgnoreThreadBlock: false
            sd:
                Name: Sound Devices
                Exec: mmsys.cpl.lnk
                Args: ~
                Path: QC
                Delay: 0
                IgnoreThreadBlock: false
            a:
                Name: Windows Activation
                Exec: slui.lnk
                Args: ~
                Path: QC
                Delay: 0
                IgnoreThreadBlock: false
            sw:
                Name: System Window (PC Summary)
                Exec: controlsys.lnk
                Args: ~
                Path: QC
                Delay: 0
                IgnoreThreadBlock: false
            u:
                Name: Windows Update
                Exec: msupdate.url
                Args: ~
                Path: QC
                Delay: 2500
                IgnoreThreadBlock: false
            e:
                Name: Windows Explorer
                Exec: explorer.lnk
                Args: ~
                Path: QC
                Delay: 0
                IgnoreThreadBlock: false
            

    # Utility suite command configuration
    Utility:
        SrcCopy: true
        SrcModeRoot: UTILITIES
        DstModeRoot: "%USERPROFILE%\\Desktop\\Utilities"

        Commands:
            r:
                Name: Revo Uninstaller
                Exec: RevoUPort.exe
                Args: ~
                Path: Revo Uninstaller
                Delay: 0
                IgnoreThreadBlock: false
            dn:
                Name: DDU (NVIDIA)
                Exec: DDU_NV.bat
                Args: ~
                Path: DDU
                Delay: 0
                IgnoreThreadBlock: false
            da:
                Name: DDU (AMD)
                Exec: DDU_AMD.bat
                Args: ~
                Path: DDU
                Delay: 0
                IgnoreThreadBlock: false


# Program macros for sequential execution
Macros:
    F:
        Name: Prime + Furmark
        SetMode: "!t"
        Command: p f m
    G: 
        Name: Standard Testing
        SetMode: "!t"
        Command: a f25 m | s
    Q:
        Name: QC Windows
        SetMode: "!q"
        Command: dv ds sw e u

...