# Configuration file for ScriptEx
#
# Written by Haohan Liu (c) 2020


---
# Program parameters. Only change these if you know what
# you are doing or aren't afraid to break something.
Program:
    # If an invalid command is found in the input, no
    # commands will run. Change this if you want input
    # containing invalid commands to still run valid
    # inputs. 
    IgnoreInvalidCommands: false

    # The speed at which the title animation runs.
    # Less is faster, more is slower.
    TitleScreenDelay: 20

    # Invoke key must be used at the start of an input.
    # When detected, all input will be directed to the
    # Shelleton interface. 
    InvokeKey: "/"

    # Shelleton commands to run at program startup.
    StartupCommands:
        - Startup.SetPerformanceMode true
        - Startup.AutoWinUpdate true
        - Startup.EnableAutoStart true
        - Startup.RunSystemCheck false

    # Default starting mode of the program. This mode
    # will be selected if no valid mode is requested
    # at the title screen.
    DefaultMode: "!s"

    # Command keys to change the mode of the program.
    ModeKeys:
        "!s": Software
        "!t": Testing
        "!u": Utility
        "!q": QC

    # Command keys with special functionality within
    # the program. 
    SpecialKeys:
        "|": Threadblock
        "?": Show Commands
      
      
# RoboCopy operating parameters
RoboCopy:
    # Configure this to match your storage device. 
    # Only change SrcDriveRoot if all SrcModeRoot paths are
    # in a subdirectory within the drive.
    SrcDriveName: SAMSUNG USB
    SrcDriveRoot: ~
    SrcDriveType: Removable 

    # Only for testing purposes. Program will automatically
    # fall back to any removable media devices if main
    # source is not found.
    ForceSrcDriveLetter: false
    SrcDriveLetter: D

    # Program will compare local and network folder creation times
    # and choose the newest to copy. 
    # Network must be public and not require credentials.
    SrcUseNetwork: true


# Each operating mode will contain its own set of commands.
# When creating new commands, follow the convention of lowercase
# keys for Mode commands and uppercase keys for Macro commands.
Modes:

    # Software installation mode.
    # Contains commands pertaining to system software
    # and driver installations. 
    Software:
        SrcCopy: true
        SrcModeRoot: SOFTWARE
        NetModeRoot: "\\\\LIU-WORKSTATION\\Software"
        DstModeRoot: "%USERPROFILE%\\Desktop\\Setup"

        Categories:
            - driver
            - lighting

        Commands:
            # Hardware Drivers
            nv:
                Name: NVIDIA GPU Driver
                Category: driver
                Exec: setup.exe
                Args: -noreboot -nosplash
                SrcPath: _NVIDIA GPU
                NetPath: Nvidia
                Delay: 0
                IgnoreThreadBlock: false
            na:
                Name: NVIDIA GPU Auto Installer
                Category: driver
                Exec: NV_INSTALL.exe
                Args: ~
                SrcPath: _NVIDIA AUTO
                NetPath: Nvidia Auto
                Delay: 0
                IgnoreThreadBlock: false
            amd:
                Name: AMD GPU Driver
                Category: driver
                Exec: Setup.exe
                Args: ~
                SrcPath: _AMD GPU
                NetPath: AMD
                Delay: 0
                IgnoreThreadBlock: false
            amds:
                Name: AMD GPU Driver (silent)
                Category: driver
                Exec: Setup.exe
                Args: -INSTALL
                SrcPath: _AMD GPU
                NetPath: AMD
                Delay: 0
                IgnoreThreadBlock: false
            amc:
                Name: AMD Chipset Driver
                Category: driver
                Exec: "*.exe"
                Args: ~
                SrcPath: _AMD Chipset
                NetPath: AMD Chipset
                Delay: 0
                IgnoreThreadBlock: false
            ig:
                Name: Intel iGPU Driver
                Category: driver
                Exec: igxpin.exe
                Args: -s -overwrite
                SrcPath: _INTEL iGPU
                NetPath: Intel
                Delay: 0
                IgnoreThreadBlock: false
    
            # Lighting Software
            aw:
                Name: AMD Wraith Prism (manual)
                Category: lighting
                Exec: Setup.exe
                Args: ~
                SrcPath: AMD Wraith Prism
                NetPath: Wraith Prism
                Delay: 0
                IgnoreThreadBlock: false
            au:
                Name: ASUS Aura
                Category: lighting
                Exec: AsusSetup.exe
                Args: /s /SMS
                SrcPath: ASUS Aura
                NetPath: Aura
                Delay: 0
                IgnoreThreadBlock: false
            aug:
                Name: ASUS Aura (GPU Only)
                Category: lighting
                Exec: AsusSetup.exe
                Args: /s /SMS
                SrcPath: ASUS Aura GPU
                NetPath: Aura GPU
                Delay: 0
                IgnoreThreadBlock: false
            ac:
                Name: ASUS Armory Crate
                Category: lighting
                Exec: "*.exe"
                Args: ~
                SrcPath: ASUS Armory Crate
                NetPath: Armory Crate
                Delay: 0
                IgnoreThreadBlock: false
            al:
                Name: ASUS LiveDash
                Category: lighting
                Exec: AsusSetup.exe
                Args: /s /SMS
                SrcPath: ASUS LiveDash
                NetPath: Livedash
                Delay: 0
                IgnoreThreadBlock: false
            cm:
                Name: CM MasterPlus
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP-
                SrcPath: CM MasterPlus
                NetPath: MasterPlus
                Delay: 0
                IgnoreThreadBlock: false
            tb:
                Name: TEAM Blitz
                Category: lighting
                Exec: Setup.exe
                Args: /s /SMS
                SrcPath: TEAM Blitz
                NetPath: Blitz
                Delay: 0
                IgnoreThreadBlock: false
            ci:
                Name: CORSAIR iCUE
                Category: lighting
                Exec: "*.msi"
                Args: /qb
                SrcPath: CORSAIR iCUE
                NetPath: iCUE
                Delay: 0
                IgnoreThreadBlock: false
            mm:
                Name: MSI Mystic Light
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP- 
                SrcPath: MSI Mystic Light
                NetPath: Mystic Light
                Delay: 0
                IgnoreThreadBlock: false
            md2:
                Name: MSI Dragon Center v2
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP- 
                SrcPath: MSI Dragon Center 2
                NetPath: Dragon Center
                Delay: 0
                IgnoreThreadBlock: false
            md2s:
                Name: MSI Dragon Center OneDC_SDK
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP- 
                SrcPath: MSI OneDC_SDK
                NetPath: OneDC_SDK
                Delay: 0
                IgnoreThreadBlock: false
            nc:
                Name: NZXT CAM
                Category: lighting
                Exec: "*.exe"
                Args: ~ 
                SrcPath: NZXT CAM
                NetPath: CAM
                Delay: 0
                IgnoreThreadBlock: false
            gr:
                Name: GIGABYTE RGBFusion
                Category: lighting
                Exec: UpdPack.exe
                Args: ~
                SrcPath: GIGABYTE RGBFusion
                NetPath: RGBFusion
                Delay: 0
                IgnoreThreadBlock: false
            ga:
                Name: GIGABYTE Aorus Engine
                Category: lighting
                Exec: "*.exe"
                Args: /SILENT /NORESTART /SP-
                SrcPath: GIGABYTE Aorus Engine
                NetPath: Aorus Engine
                Delay: 0
                IgnoreThreadBlock: false

    # Testing mode.
    # Contains commands pertaining to system stress testing
    # and benchmarking. 
    Testing:
        SrcCopy: false
        SrcModeRoot: AAA Testing
        NetModeRoot: ~
        DstModeRoot: "%USERPROFILE%\\Desktop\\AAA Testing"

        Categories:
            - cpu + ram
            - gpu
            - other

        Commands:
            p:
                Name: Prime95 (Blend)
                Category: cpu + ram
                Exec: prime95.exe
                Args: -t
                SrcPath: Benchmark
                Delay: 5000
                IgnoreThreadBlock: false
            f:
                Name: Furmark (inf)
                Category: gpu
                Exec: FurMark.exe
                Args: /nogui /msaa=8 /width=1280 height=720 /xtreme_burning
                SrcPath: Benchmark
                Delay: 0
                IgnoreThreadBlock: false
            f15:
                Name: Furmark (15 min)
                Category: gpu
                Exec: FurMark.exe
                Args: /nogui /msaa=8 /width=1280 height=720 /max_time=900000 /xtreme_burning
                SrcPath: Benchmark
                Delay: 0
                IgnoreThreadBlock: false
            f25:
                Name: Furmark (25 min)
                Category: gpu
                Exec: FurMark.exe
                Args: /nogui /msaa=8 /width=1280 height=720 /max_time=1500000 /xtreme_burning
                SrcPath: Benchmark
                Delay: 0
                IgnoreThreadBlock: false
            a:
                Name: AIDA64 Stability Test (inf)
                Category: cpu + ram
                Exec: aida64.exe
                Args: /SST CPU,FPU,Cache,RAM
                SrcPath: AIDA64
                Delay: 1000
                IgnoreThreadBlock: false
            a15:
                Name: AIDA64 Stability Test (15 min)
                Category: cpu + ram
                Exec: aida64.exe
                Args: /SST CPU,FPU,Cache,RAM /SSTDUR 15
                SrcPath: AIDA64
                Delay: 1000
                IgnoreThreadBlock: false
            a25:
                Name: AIDA64 Stability Test (25 min)
                Category: cpu + ram
                Exec: aida64.exe
                Args: /SST CPU,FPU,Cache,RAM /SSTDUR 25
                SrcPath: AIDA64
                Delay: 1000
                IgnoreThreadBlock: false
            m:
                Name: HWMonitor
                Category: other
                Exec: HWMonitor_x64.exe
                Args: ~
                SrcPath: Benchmark
                Delay: 0
                IgnoreThreadBlock: true
            s:
                Name: Superposition
                Category: gpu
                Exec: launcher.exe
                Args: ~
                SrcPath: Benchmark\Superposition\bin
                Delay: 0
                IgnoreThreadBlock: false
            h:
                Name: Heaven
                Category: gpu
                Exec: heaven_modified.bat
                Args: ~
                SrcPath: Benchmark\Heaven
                Delay: 0
                IgnoreThreadBlock: false
            i:
                Name: Intel Burn Test V2
                Category: cpu + ram
                Exec: IntelBurnTestV2.exe
                Args: ~
                SrcPath: "IBT\\IntelBurnTestV2.New"
                Delay: 0
                IgnoreThreadBlock: false
            
    # QC mode.
    # Contains commands pertaining to finalising a system
    # for the final quality control phase. 
    QC:
        SrcCopy: false
        SrcModeRoot: AAA Testing
        NetModeRoot: ~
        DstModeRoot: "%USERPROFILE%\\Desktop\\AAA Testing"
            
        Commands:
            t:
                Name: Task Manager
                Exec: Task Manager.lnk
                Args: ~
                SrcPath: QC
                Delay: 0
                IgnoreThreadBlock: false
            dv:
                Name: Device Manager
                Exec: devmgmt.msc.lnk
                Args: ~
                SrcPath: QC
                Delay: 0
                IgnoreThreadBlock: false
            ds:
                Name: Disk Management
                Exec: diskmgmt.msc.lnk
                Args: ~
                SrcPath: QC
                Delay: 0
                IgnoreThreadBlock: false
            sd:
                Name: Sound Devices
                Exec: mmsys.cpl.lnk
                Args: ~
                SrcPath: QC
                Delay: 0
                IgnoreThreadBlock: false
            a:
                Name: Windows Activation
                Exec: slui.lnk
                Args: ~
                SrcPath: QC
                Delay: 0
                IgnoreThreadBlock: false
            sw:
                Name: System Window (PC Summary)
                Exec: controlsys.lnk
                Args: ~
                SrcPath: QC
                Delay: 0
                IgnoreThreadBlock: false
            u:
                Name: Windows Update
                Exec: msupdate.url
                Args: ~
                SrcPath: QC
                Delay: 2500
                IgnoreThreadBlock: false
            e:
                Name: Windows Explorer
                Exec: explorer.lnk
                Args: ~
                SrcPath: QC
                Delay: 0
                IgnoreThreadBlock: false
            

    # Utility mode.
    # Contains commands pertaining to activities outside of
    # software installation, testing, or quality control. 
    Utility:
        SrcCopy: true
        SrcModeRoot: UTILITIES
        NetModeRoot: ~
        DstModeRoot: "%USERPROFILE%\\Desktop\\Utilities"

        Commands:
            r:
                Name: Revo Uninstaller
                Exec: RevoUPort.exe
                Args: ~
                SrcPath: Revo Uninstaller
                Delay: 0
                IgnoreThreadBlock: true
            d:
                Name: DDU (Manual)
                Exec: "*.exe"
                Args: ~
                SrcPath: DDU
                Delay: 0
                IgnoreThreadBlock: false
            dn:
                Name: DDU (NVIDIA)
                Exec: DDU_NV.bat
                Args: ~
                SrcPath: DDU
                Delay: 0
                IgnoreThreadBlock: false
            da:
                Name: DDU (AMD)
                Exec: DDU_AMD.bat
                Args: ~
                SrcPath: DDU
                Delay: 0
                IgnoreThreadBlock: false


# Macros execute a line of commands as they would be executed
# from the terminal. SetMode ensures the macro will begin
# running in the correct Mode. 
#
# When creating new commands, follow the convention of lowercase
# keys for Mode commands and uppercase keys for Macro commands.
Macros:
    F:
        Name: Prime + Furmark
        SetMode: "!t"
        Command: p f m
    G: 
        Name: Standard Testing
        SetMode: "!t"
        Command: a f25 m | s
    Q:
        Name: Open QC Windows
        SetMode: "!q"
        Command: dv ds sw e u

...